### PR TITLE
feat: additional getter methods

### PR DESCRIPTION
**Pull request by drahnr**
Initial stab on better user visible types. Partially required to impl `repomd` format as part of https://github.com/drahnr/cantaloupe .

Ref #9

### CODE REVIEW

**Comment by drahnr** [comment]
Builds on top of #27 which is ready for review, this one is WIP and needs restructuring.

**Comment by drahnr** [comment]
This PR is not dead :) going to pick this up in a few days

**Comment by dralley** [comment]
@drahnr I also need these (for the same reason) but I've got plenty of other things that I still need to work on so it's not an immediate blocker.

**Comment by drahnr** [comment]
@Richterrettich did a quick cleanup, two commits, one for generic i64 value infra, the other for better digest handling resolving a TODO.

**Comment by dacut** [comment]
I have merged this into a fork since this seems to be abandoned for now.
https://docs.rs/kanga-rpm-rs/0.7.0/rpm/

**Pull request merged**
